const IMAGES = {
  cybersoftImage: require('./cybersoft.png'),
  allBody: {
    bikiniBra: require('./allbody/bikini_bra.png'),
    bikiniBraNew: require('./allbody/bikini_branew.png'),
    bikiniPants: require('./allbody/bikini_pants.png'),
    bikiniPantsNew: require('./allbody/bikini_pantsnew.png'),
    body: require('./allbody/body.png'),
    bodyNew: require('./allbody/bodynew.png'),
    feetHighLeft: require('./allbody/feet_high_left.png'),
    feetHighLeftNew: require('./allbody/feet_high_leftnew.png'),
    feetHighRight: require('./allbody/feet_high_right.png'),
    feetHighRightNew: require('./allbody/feet_high_rightnew.png'),
  },
  backGround: {
    background998: require('./background/background_998.jpg'),
    background1: require('./background/background1.jpg'),
    background2: require('./background/background2.jpg'),
    background3: require('./background/background3.jpg'),
    background4: require('./background/background4.jpg'),
    background5: require('./background/background5.jpg'),
    background6: require('./background/background6.jpg'),
    background7: require('./background/background7.jpg'),
    background1_show: require('./background/background1_show.jpg'),
    background2_show: require('./background/background2_show.jpg'),
    background3_show: require('./background/background3_show.jpg'),
    background4_show: require('./background/background4_show.jpg'),
    background5_show: require('./background/background5_show.jpg'),
    background6_show: require('./background/background6_show.jpg'),
    background7_show: require('./background/background7_show.jpg'),
  },
  clothes: {
    botcloth1: require('./clothes/botcloth1.png'),
    botcloth2: require('./clothes/botcloth2.png'),
    botcloth3: require('./clothes/botcloth3.png'),
    botcloth4: require('./clothes/botcloth4.png'),
    botcloth5: require('./clothes/botcloth5.png'),
    topcloth1: require('./clothes/topcloth1.png'),
    topcloth2: require('./clothes/topcloth2.png'),
    topcloth3: require('./clothes/topcloth3.png'),
    topcloth4: require('./clothes/topcloth4.png'),
    topcloth5: require('./clothes/topcloth5.png'),
    topcloth6: require('./clothes/topcloth6.png'),
    botcloth_show1: require('./clothes/botcloth1_show.jpg'),
    botcloth_show2: require('./clothes/botcloth2_show.jpg'),
    botcloth_show3: require('./clothes/botcloth3_show.jpg'),
    botcloth_show4: require('./clothes/botcloth4_show.jpg'),
    botcloth_show5: require('./clothes/botcloth5_show.jpg'),
    topcloth_show1: require('./clothes/topcloth1_show.jpg'),
    topcloth_show2: require('./clothes/topcloth2_show.jpg'),
    topcloth_show3: require('./clothes/topcloth3_show.jpg'),
    topcloth_show4: require('./clothes/topcloth4_show.jpg'),
    topcloth_show5: require('./clothes/topcloth5_show.jpg'),
    topcloth_show6: require('./clothes/topcloth6_show.jpg'),
  },
  hairStyle: {
    hairStyle1: require('./hairstyle/hairstyle1.png'),
    hairStyle2: require('./hairstyle/hairstyle2.png'),
    hairStyle3: require('./hairstyle/hairstyle3.png'),
    hairStyle_show1: require('./hairstyle/hairstyle1_show.jpg'),
    hairStyle_show2: require('./hairstyle/hairstyle2_show.jpg'),
    hairStyle_show3: require('./hairstyle/hairstyle3_show.jpg'),
  },
  handBags: {
    handBag1: require('./handbags/handbag1.png'),
    handBag2: require('./handbags/handbag2.png'),
    handBag3: require('./handbags/handbag3.png'),
    handbag_show1: require('./handbags/handbag1_show.jpg'),
    handbag_show2: require('./handbags/handbag2_show.jpg'),
    handbag_show3: require('./handbags/handbag3_show.jpg'),
  },
  model: {
    999: require('./model/999.png'),
    1000: require('./model/1000.png'),
    '1000new': require('./model/1000.png'),
    1003: require('./model/1003.png'),
  },
  necklaces: {
    neckLace1: require('./necklaces/necklace1.png'),
    neckLace2: require('./necklaces/necklace2.png'),
    neckLace3: require('./necklaces/necklace3.png'),
    neckLaceShow1: require('./necklaces/necklace1_show.jpg'),
    neckLaceShow2: require('./necklaces/necklace2_show.jpg'),
    neckLaceShow3: require('./necklaces/necklace3_show.jpg'),
  },
  shoes: {
    shoes_show1: require('./shoes/shoes1_show.jpg'),
    shoes_show2: require('./shoes/shoes2_show.jpg'),
    shoes_show3: require('./shoes/shoes3_show.jpg'),
    shoes_show4: require('./shoes/shoes4_show.jpg'),
    shoes_show5: require('./shoes/shoes5_show.jpg'),
    shoes1: require('./shoes/shoes1.png'),
    shoes2: require('./shoes/shoes2.png'),
    shoes3: require('./shoes/shoes3.png'),
    shoes4: require('./shoes/shoes4.png'),
    shoes5: require('./shoes/shoes5.png'),
  },
};

export default IMAGES;
